- name: Add Oranchelo repisotry
  apt_repository:
    repo: "ppa:oranchelo/oranchelo-icon-theme"
    state: present

- name: Install Oranchelo icons
  apt:
    name: oranchelo-icon-theme
    state: present

- name: Install Numix GTK
  apt:
    name: numix-gtk-theme
    state: present

- name: Install prerequisites for polybar
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - cmake
    - cmake-data
    - libcairo2-dev
    - libxcb1-dev
    - libxcb-ewmh-dev
    - libxcb-icccm4-dev
    - libxcb-image0-dev
    - libxcb-randr0-dev
    - libxcb-util0-dev
    - libxcb-xkb-dev
    - pkg-config
    - python-xcbgen
    - xcb-proto
    - libxcb-xrm-dev
    - libasound2-dev
    - libmpdclient-dev
    - libiw-dev
    - libcurl4-openssl-dev
    - libpulse-dev
    - libxcb-composite0-dev

- name: Install polybar
  shell: |
    cd /tmp
    wget https://github.com/jaagr/polybar/releases/download/3.4.0/polybar-3.4.0.tar
    tar -xf polybar*.tar
    cd polybar
    ./build.sh -f -A
